#!/bin/bash

brew install python3 neovim tmux tmuxinator zplug git rust go alacritty python fzf gitui gnu-sed rigrep fd reattach-to-user-namespace luarocks bat
brew tap shaunsingh/SFMono-Nerd-Font-Ligaturized
brew install --cask font-sf-mono-nerd-font-ligaturized

pip3 install tiktoken shell-gpt==0.9.1
