#!/bin/bash

brew install python3 neovim tmux tmuxinator zplug git rust go alacritty python fzf gitui gnu-sed rigrep fd reattach-to-user-namespace luarocks
brew install --cask font-victor-mono

pip3 install tiktoken shell-gpt==0.9.1
